server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   # 开启检索服务名
      routes:
        - id: payment_routh          # id 区别不同的名称用
          #uri: http://localhost:8001 # 真实地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:                # 断言
            - Path=/payment/get/**   # 路由规则
        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/**
            - After=2021-03-02T15:36:29.588+08:00[Asia/Shanghai]
            - Before=2021-03-02T15:36:29.588+08:00[Asia/Shanghai]
            - Between=2021-03-02T15:36:29.588+08:00[Asia/Shanghai],2021-03-02T15:36:29.588+08:00[Asia/Shanghai]
            - Cookie=username,niushuai233
            - Header=X-Request-Id, \d+
            - Method=GET
            - Host=*.baidu.com
            - Query=username
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
