server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinal-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.207.128:8848
    sentinel:
      transport:
        dashboard: 192.168.207.128:8080
        port: 8719
management:
  endpoints:
    web:
      exposure:
        include: "*"
